import TSClassParser from '../../TSClassParser';
import MarkdownGenerator from '../../MarkdownGenerator';

const file = 'api-gen/__tests__/fixtures/EnumTypeComposer.d.ts';

it('markdown TypeStorage.d.ts', () => {
  const data = TSClassParser.parseFile(file);
  expect(MarkdownGenerator.generate(data.class, data.interfaces)).toMatchInlineSnapshot(`
"---
id: EnumTypeComposer
title: EnumTypeComposer
---

<!-- 
🛑🛑🛑
DO NOT EDIT THIS FILE!
IT WAS AUTOGENERATED FROM d.ts FILE

If you want to make changes in this file, please do it via
https://github.com/graphql-compose/graphql-compose/blob/master/src/EnumTypeComposer.d.ts
-->

## Static methods

### static create()

\`\`\`js
static create(
  typeDef: any,
  schemaComposer: any,
): EnumTypeComposer<TCtx>
\`\`\`

### static createTemp()

\`\`\`js
static createTemp(
  typeDef: any,
  schemaComposer: any,
): EnumTypeComposer<TCtx>
\`\`\`

## Properties

### schemaComposer

\`\`\`js
schemaComposer: any;
\`\`\`

## Methods

### hasField()

\`\`\`js
hasField(
  name: string,
): boolean
\`\`\`

### getFields()

\`\`\`js
getFields(): any
\`\`\`

### getField()

\`\`\`js
getField(
  name: string,
): any
\`\`\`

### getFieldNames()

\`\`\`js
getFieldNames(): string[]
\`\`\`

### setFields()

\`\`\`js
setFields(
  values: any,
): this
\`\`\`

### setField()

\`\`\`js
setField(
  name: string,
  valueConfig: any,
): this
\`\`\`

### addFields()

\`\`\`js
addFields(
  newValues: any,
): this
\`\`\`

### removeField()

\`\`\`js
removeField(
  nameOrArray: string | string[],
): this
\`\`\`

### removeOtherFields()

\`\`\`js
removeOtherFields(
  fieldNameOrArray: string | string[],
): this
\`\`\`

### reorderFields()

\`\`\`js
reorderFields(
  names: string[],
): this
\`\`\`

### extendField()

\`\`\`js
extendField(
  name: string,
  partialValueConfig: Partial<any>,
): this
\`\`\`

### deprecateFields()

\`\`\`js
deprecateFields(
  fields: string | string[] | { [fieldName: string]: string; },
): this
\`\`\`

### getExtensions()

\`\`\`js
getExtensions(): any
\`\`\`

### setExtensions()

\`\`\`js
setExtensions(
  extensions: any,
): this
\`\`\`

### extendExtensions()

\`\`\`js
extendExtensions(
  extensions: any,
): this
\`\`\`

### clearExtensions()

\`\`\`js
clearExtensions(): this
\`\`\`

### getExtension()

\`\`\`js
getExtension(
  extensionName: string,
): any
\`\`\`

### hasExtension()

\`\`\`js
hasExtension(
  extensionName: string,
): boolean
\`\`\`

### setExtension()

\`\`\`js
setExtension(
  extensionName: string,
  value: any,
): this
\`\`\`

### removeExtension()

\`\`\`js
removeExtension(
  extensionName: string,
): this
\`\`\`

### getType()

\`\`\`js
getType(): any
\`\`\`

### getTypePlural()

\`\`\`js
getTypePlural(): any
\`\`\`

### getTypeNonNull()

\`\`\`js
getTypeNonNull(): any
\`\`\`

### getTypeName()

\`\`\`js
getTypeName(): string
\`\`\`

### setTypeName()

\`\`\`js
setTypeName(
  name: string,
): this
\`\`\`

### getDescription()

\`\`\`js
getDescription(): string
\`\`\`

### setDescription()

\`\`\`js
setDescription(
  description: string,
): this
\`\`\`

### clone()

\`\`\`js
clone(
  newTypeName: string,
): EnumTypeComposer<TContext>
\`\`\`

## Internal type definitions

###  ComposeEnumTypeConfig

\`\`\`js
export type ComposeEnumTypeConfig = GraphQLEnumTypeConfig & {
  extensions?: Extensions;
};
\`\`\`

###  EnumTypeComposeDefinition

\`\`\`js
export type EnumTypeComposeDefinition = TypeAsString | ComposeEnumTypeConfig | GraphQLEnumType;
\`\`\`

###  GraphQLEnumTypeExtended

\`\`\`js
export type GraphQLEnumTypeExtended = GraphQLEnumType & {
  _gqcExtensions?: Extensions;
};
\`\`\`

"
`);
});

it('parse EnumTypeComposer.d.ts', () => {
  expect(TSClassParser.parseFile(file)).toMatchInlineSnapshot(`
Object {
  "class": Object {
    "constructors": Array [
      Object {
        "documentation": "",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "gqType",
            "type": "any",
          },
          Object {
            "documentation": "",
            "name": "schemaComposer",
            "type": "any",
          },
        ],
        "type": "EnumTypeComposer<TContext>",
      },
    ],
    "documentation": "",
    "methods": Array [
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "hasField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
          },
        ],
        "type": "boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getFields",
        "parameters": Array [],
        "type": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
          },
        ],
        "type": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getFieldNames",
        "parameters": Array [],
        "type": "string[]",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "setFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "values",
            "type": "any",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "setField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
          },
          Object {
            "documentation": "",
            "name": "valueConfig",
            "type": "any",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "addFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "newValues",
            "type": "any",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "removeField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "nameOrArray",
            "type": "string | string[]",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "removeOtherFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldNameOrArray",
            "type": "string | string[]",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "reorderFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "names",
            "type": "string[]",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "extendField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
          },
          Object {
            "documentation": "",
            "name": "partialValueConfig",
            "type": "Partial<any>",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "deprecateFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fields",
            "type": "string | string[] | { [fieldName: string]: string; }",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getExtensions",
        "parameters": Array [],
        "type": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "setExtensions",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensions",
            "type": "any",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "extendExtensions",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensions",
            "type": "any",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "clearExtensions",
        "parameters": Array [],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
          },
        ],
        "type": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "hasExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
          },
        ],
        "type": "boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "setExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
          },
          Object {
            "documentation": "",
            "name": "value",
            "type": "any",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "removeExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getType",
        "parameters": Array [],
        "type": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getTypePlural",
        "parameters": Array [],
        "type": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getTypeNonNull",
        "parameters": Array [],
        "type": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getTypeName",
        "parameters": Array [],
        "type": "string",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "setTypeName",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "getDescription",
        "parameters": Array [],
        "type": "string",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "setDescription",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "description",
            "type": "string",
          },
        ],
        "type": "this",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "clone",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "newTypeName",
            "type": "string",
          },
        ],
        "type": "EnumTypeComposer<TContext>",
      },
    ],
    "name": "EnumTypeComposer",
    "properties": Array [
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": false,
        },
        "name": "schemaComposer",
        "type": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": true,
          "readonly": false,
          "static": false,
        },
        "name": "gqType",
        "type": "any",
      },
    ],
    "staticMethods": Array [
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": true,
        },
        "name": "create",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "typeDef",
            "type": "any",
          },
          Object {
            "documentation": "",
            "name": "schemaComposer",
            "type": "any",
          },
        ],
        "type": "EnumTypeComposer<TCtx>",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "private": false,
          "protected": false,
          "readonly": false,
          "static": true,
        },
        "name": "createTemp",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "typeDef",
            "type": "any",
          },
          Object {
            "documentation": "",
            "name": "schemaComposer",
            "type": "any",
          },
        ],
        "type": "EnumTypeComposer<TCtx>",
      },
    ],
    "staticProperties": Array [],
    "type": "typeof EnumTypeComposer",
  },
  "interfaces": Array [
    Object {
      "code": "

export type ComposeEnumTypeConfig = GraphQLEnumTypeConfig & {
  extensions?: Extensions;
};",
      "name": " ComposeEnumTypeConfig",
    },
    Object {
      "code": "

export type EnumTypeComposeDefinition = TypeAsString | ComposeEnumTypeConfig | GraphQLEnumType;",
      "name": " EnumTypeComposeDefinition",
    },
    Object {
      "code": "

export type GraphQLEnumTypeExtended = GraphQLEnumType & {
  _gqcExtensions?: Extensions;
};",
      "name": " GraphQLEnumTypeExtended",
    },
  ],
}
`);
});
