import TSClassParser from '../../TSClassParser';
import MarkdownGenerator from '../../MarkdownGenerator';

const file = 'api-gen/__tests__/fixtures/ObjectTypeComposer.d.ts';

it('markdown ObjectTypeComposer.d.ts', () => {
  const data = TSClassParser.parseFile(file);
  expect(MarkdownGenerator.generate(data.classData, data.interfaces)).toMatchInlineSnapshot(`
"---
id: ObjectTypeComposer
title: ObjectTypeComposer
---

<!-- 
🛑🛑🛑
DO NOT EDIT THIS FILE!
IT WAS AUTOGENERATED FROM d.ts FILE
🛑🛑🛑
If you want to make changes in this file, please do it via
https://github.com/graphql-compose/graphql-compose/blob/master/src/ObjectTypeComposer.d.ts
-->

## Static methods

### static create()

\`\`\`js
static create<TSrc = any, TCtx = any>(
  typeDef: ObjectTypeComposeDefinition<TSrc, TCtx>,
  schemaComposer: SchemaComposer<TCtx>
): ObjectTypeComposer<TSrc, TCtx>
\`\`\`

### static createTemp()

\`\`\`js
static createTemp<TSrc = any, TCtx = any>(
  typeDef: ObjectTypeComposeDefinition<TSrc, TCtx>,
  schemaComposer: SchemaComposer<TCtx>
): ObjectTypeComposer<TSrc, TCtx>
\`\`\`

## Properties

### schemaComposer

\`\`\`js
schemaComposer: SchemaComposer<TContext>;
\`\`\`

## Field methods

### getFields()

\`\`\`js
getFields(): ComposeFieldConfigMap<TSource, TContext>
\`\`\`

### getFieldNames()

\`\`\`js
getFieldNames(): string[]
\`\`\`

### setFields()

\`\`\`js
setFields(
  fields: ComposeFieldConfigMap<TSource, TContext>
): this
\`\`\`

### hasField()

\`\`\`js
hasField(
  fieldName: string
): boolean
\`\`\`

### setField()

\`\`\`js
setField<TArgs = ArgsMap>(
  fieldName: string,
  fieldConfig: ComposeFieldConfig<TSource, TContext, TArgs>
): this
\`\`\`

### addFields()

\`\`\`js
addFields(
  newFields: ComposeFieldConfigMap<TSource, TContext>
): this
\`\`\`

Add new fields or replace existed in a GraphQL type

### addNestedFields()

\`\`\`js
addNestedFields(
  newFields: ComposeFieldConfigMap<TSource, TContext>
): this
\`\`\`

Add new fields or replace existed (where field name may have dots)

### getField()

\`\`\`js
getField<TArgs = ArgsMap>(
  fieldName: string
): ComposeFieldConfig<TSource, TContext, TArgs>
\`\`\`

### removeField()

\`\`\`js
removeField(
  fieldNameOrArray: string | string[]
): this
\`\`\`

### removeOtherFields()

\`\`\`js
removeOtherFields(
  fieldNameOrArray: string | string[]
): this
\`\`\`

### extendField()

\`\`\`js
extendField<TArgs = ArgsMap>(
  fieldName: string,
  partialFieldConfig: Partial<ComposeFieldConfig<TSource, TContext, TArgs>>
): this
\`\`\`

### reorderFields()

\`\`\`js
reorderFields(
  names: string[]
): this
\`\`\`

### isFieldNonNull()

\`\`\`js
isFieldNonNull(
  fieldName: string
): boolean
\`\`\`

### getFieldConfig()

\`\`\`js
getFieldConfig(
  fieldName: string
): GraphQLFieldConfig<TSource, TContext>
\`\`\`

### getFieldType()

\`\`\`js
getFieldType(
  fieldName: string
): GraphQLOutputType
\`\`\`

### getFieldTC()

\`\`\`js
getFieldTC(
  fieldName: string
): ObjectTypeComposer<TSource, TContext>
\`\`\`

### makeFieldNonNull()

\`\`\`js
makeFieldNonNull(
  fieldNameOrArray: string | string[]
): this
\`\`\`

### makeFieldNullable()

\`\`\`js
makeFieldNullable(
  fieldNameOrArray: string | string[]
): this
\`\`\`

### deprecateFields()

\`\`\`js
deprecateFields(
  fields: {
      [fieldName: string]: string;
  } | string[] | string
): this
\`\`\`

### getFieldArgs()

\`\`\`js
getFieldArgs(
  fieldName: string
): GraphQLFieldConfigArgumentMap
\`\`\`

### hasFieldArg()

\`\`\`js
hasFieldArg(
  fieldName: string,
  argName: string
): boolean
\`\`\`

### getFieldArg()

\`\`\`js
getFieldArg(
  fieldName: string,
  argName: string
): GraphQLArgumentConfig
\`\`\`

### getFieldArgType()

\`\`\`js
getFieldArgType(
  fieldName: string,
  argName: string
): GraphQLInputType
\`\`\`

## Type methods

### getType()

\`\`\`js
getType(): GraphQLObjectType
\`\`\`

### getTypePlural()

\`\`\`js
getTypePlural(): GraphQLList<GraphQLObjectType>
\`\`\`

### getTypeNonNull()

\`\`\`js
getTypeNonNull(): GraphQLNonNull<GraphQLObjectType>
\`\`\`

### getTypeName()

\`\`\`js
getTypeName(): string
\`\`\`

### setTypeName()

\`\`\`js
setTypeName(
  name: string
): this
\`\`\`

### getDescription()

\`\`\`js
getDescription(): string
\`\`\`

### setDescription()

\`\`\`js
setDescription(
  description: string
): this
\`\`\`

### clone()

\`\`\`js
clone<TCloneSource = TSource>(
  newTypeName: string
): ObjectTypeComposer<TCloneSource, TContext>
\`\`\`

### getIsTypeOf()

\`\`\`js
getIsTypeOf(): GraphQLIsTypeOfFn<TSource, TContext> | null | void
\`\`\`

### setIsTypeOf()

\`\`\`js
setIsTypeOf(
  fn: GraphQLIsTypeOfFn<any, any> | null | void
): this
\`\`\`

## InputType methods

### getInputType()

\`\`\`js
getInputType(): GraphQLInputObjectType
\`\`\`

### hasInputTypeComposer()

\`\`\`js
hasInputTypeComposer(): boolean
\`\`\`

### setInputTypeComposer()

\`\`\`js
setInputTypeComposer(
  itc: InputTypeComposer<TContext>
): this
\`\`\`

### getInputTypeComposer()

\`\`\`js
getInputTypeComposer(): InputTypeComposer<TContext>
\`\`\`

### getITC()

\`\`\`js
getITC(): InputTypeComposer<TContext>
\`\`\`

### removeInputTypeComposer()

\`\`\`js
removeInputTypeComposer(): this
\`\`\`

## Resolver methods

### getResolvers()

\`\`\`js
getResolvers(): Map<string, Resolver<any, TContext, any>>
\`\`\`

### hasResolver()

\`\`\`js
hasResolver(
  name: string
): boolean
\`\`\`

### getResolver()

\`\`\`js
getResolver<TResolverSource = any, TArgs = ArgsMap>(
  name: string,
  middlewares: Array<ResolverMiddleware<TResolverSource, TContext, TArgs>>
): Resolver<TResolverSource, TContext, TArgs>
\`\`\`

### setResolver()

\`\`\`js
setResolver<TResolverSource = any, TArgs = ArgsMap>(
  name: string,
  resolver: Resolver<TResolverSource, TContext, TArgs>
): this
\`\`\`

### addResolver()

\`\`\`js
addResolver<TResolverSource = any, TArgs = ArgsMap>(
  resolver: Resolver<TResolverSource, TContext, TArgs> | ResolverOpts<TResolverSource, TContext, TArgs>
): this
\`\`\`

### removeResolver()

\`\`\`js
removeResolver(
  resolverName: string
): this
\`\`\`

### wrapResolver()

\`\`\`js
wrapResolver<TResolverSource = any, TArgs = ArgsMap>(
  resolverName: string,
  cbResolver: ResolverWrapCb<TResolverSource, TSource, TContext, TArgs>
): this
\`\`\`

### wrapResolverAs()

\`\`\`js
wrapResolverAs<TResolverSource = any, TArgs = ArgsMap>(
  resolverName: string,
  fromResolverName: string,
  cbResolver: ResolverWrapCb<TResolverSource, TSource, TContext, TArgs>
): this
\`\`\`

### wrapResolverResolve()

\`\`\`js
wrapResolverResolve<TResolverSource = any, TArgs = ArgsMap>(
  resolverName: string,
  cbNextRp: ResolverNextRpCb<TResolverSource, TContext, TArgs>
): this
\`\`\`

## Interface methods

### getInterfaces()

\`\`\`js
getInterfaces(): Array<InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType>
\`\`\`

### setInterfaces()

\`\`\`js
setInterfaces(
  interfaces: Array<InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType>
): this
\`\`\`

### hasInterface()

\`\`\`js
hasInterface(
  iface: string | InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType
): boolean
\`\`\`

### addInterface()

\`\`\`js
addInterface(
  interfaceObj: InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType
): this
\`\`\`

### removeInterface()

\`\`\`js
removeInterface(
  interfaceObj: InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType
): this
\`\`\`

## Extensions methods

### getExtensions()

\`\`\`js
getExtensions(): Extensions
\`\`\`

### setExtensions()

\`\`\`js
setExtensions(
  extensions: Extensions
): this
\`\`\`

### extendExtensions()

\`\`\`js
extendExtensions(
  extensions: Extensions
): this
\`\`\`

### clearExtensions()

\`\`\`js
clearExtensions(): this
\`\`\`

### getExtension()

\`\`\`js
getExtension(
  extensionName: string
): any
\`\`\`

### hasExtension()

\`\`\`js
hasExtension(
  extensionName: string
): boolean
\`\`\`

### setExtension()

\`\`\`js
setExtension(
  extensionName: string,
  value: any
): this
\`\`\`

### removeExtension()

\`\`\`js
removeExtension(
  extensionName: string
): this
\`\`\`

### getFieldExtensions()

\`\`\`js
getFieldExtensions(
  fieldName: string
): Extensions
\`\`\`

### setFieldExtensions()

\`\`\`js
setFieldExtensions(
  fieldName: string,
  extensions: Extensions
): this
\`\`\`

### extendFieldExtensions()

\`\`\`js
extendFieldExtensions(
  fieldName: string,
  extensions: Extensions
): this
\`\`\`

### clearFieldExtensions()

\`\`\`js
clearFieldExtensions(
  fieldName: string
): this
\`\`\`

### getFieldExtension()

\`\`\`js
getFieldExtension(
  fieldName: string,
  extensionName: string
): any
\`\`\`

### hasFieldExtension()

\`\`\`js
hasFieldExtension(
  fieldName: string,
  extensionName: string
): boolean
\`\`\`

### setFieldExtension()

\`\`\`js
setFieldExtension(
  fieldName: string,
  extensionName: string,
  value: any
): this
\`\`\`

### removeFieldExtension()

\`\`\`js
removeFieldExtension(
  fieldName: string,
  extensionName: string
): this
\`\`\`

## Misc methods

### addRelation()

\`\`\`js
addRelation<TRelationSource = any, TArgs = ArgsMap>(
  fieldName: string,
  relationOpts: RelationOpts<TRelationSource, TSource, TContext, TArgs>
): this
\`\`\`

### getRelations()

\`\`\`js
getRelations(): RelationThunkMap<any, TContext>
\`\`\`

### setRecordIdFn()

\`\`\`js
setRecordIdFn(
  fn: GetRecordIdFn<TSource, TContext>
): this
\`\`\`

### hasRecordIdFn()

\`\`\`js
hasRecordIdFn(): boolean
\`\`\`

### getRecordIdFn()

\`\`\`js
getRecordIdFn(): GetRecordIdFn<TSource, TContext>
\`\`\`

### getRecordId()

\`\`\`js
getRecordId(
  source: TSource,
  args: ArgsMap,
  context: TContext
): string | number
\`\`\`

Get function that returns record id, from provided object.

### get()

\`\`\`js
get(
  path: string | string[]
): any
\`\`\`

## Internal type definitions

### GetRecordIdFn

\`\`\`js
export type GetRecordIdFn<TSource, TContext> = (
  source: TSource,
  args: any,
  context: TContext
) => string;
\`\`\`

### GraphQLObjectTypeExtended

\`\`\`js
export type GraphQLObjectTypeExtended<TSource, TContext> = GraphQLObjectType & {
  _gqcInputTypeComposer?: InputTypeComposer<TContext>;
  _gqcResolvers?: Map<string, Resolver<TSource, TContext>>;
  _gqcGetRecordIdFn?: GetRecordIdFn<TSource, TContext>;
  _gqcRelations?: RelationThunkMap<TSource, TContext>;
  _gqcFields?: ComposeFieldConfigMap<TSource, TContext>;
  _gqcInterfaces?: Array<GraphQLInterfaceType | InterfaceTypeComposer<any, TContext>>;
  _gqcExtensions?: Extensions;
  description: string | null;
};
\`\`\`

### ComposeObjectTypeConfig

\`\`\`js
export type ComposeObjectTypeConfig<TSource, TContext> = {
  name: string;
  interfaces?: Thunk<GraphQLInterfaceType[] | null>;
  fields?: Thunk<ComposeFieldConfigMap<TSource, TContext>>;
  isTypeOf?: GraphQLIsTypeOfFn<TSource, TContext> | null;
  description?: string | null;
  isIntrospection?: boolean;
  extensions?: Extensions;
};
\`\`\`

### ComposeFieldConfigMap

\`\`\`js
// extended GraphQLFieldConfigMap
export type ComposeFieldConfigMap<TSource, TContext> = ObjMap<
  ComposeFieldConfig<TSource, TContext>
>;
\`\`\`

### ComposeFieldConfig

\`\`\`js
export type ComposeFieldConfig<TSource, TContext, TArgs = ArgsMap> =
  | ComposeFieldConfigAsObject<TSource, TContext, TArgs>
  | ComposeOutputType<any /* TReturn */, TContext>
  | Thunk<
      | ComposeFieldConfigAsObject<TSource, TContext, TArgs>
      | ComposeOutputType<any /* TReturn */, TContext>
    >;
\`\`\`

### GraphqlFieldConfigExtended

\`\`\`js
// extended GraphQLFieldConfig
export type GraphqlFieldConfigExtended<TSource, TContext> = GraphQLFieldConfig<
  TSource,
  TContext
> & { projection?: any };
\`\`\`

### ComposeFieldConfigAsObject

\`\`\`js
export type ComposeFieldConfigAsObject<TSource, TContext, TArgs = ArgsMap> = {
  type: Thunk<ComposeOutputType<any /* TReturn */, TContext>> | GraphQLOutputType;
  args?: ComposeFieldConfigArgumentMap<TArgs>;
  resolve?: GraphQLFieldResolver<TSource, TContext, TArgs>;
  subscribe?: GraphQLFieldResolver<TSource, TContext>;
  deprecationReason?: string | null;
  description?: string | null;
  astNode?: FieldDefinitionNode | null;
  extensions?: Extensions;
  [key: string]: any;
} & { $call?: void };
\`\`\`

### ComposeOutputType

\`\`\`js
// Output type should not have \`TSource\`. It should not affect on main Type source!
// extended GraphQLOutputType
export type ComposeOutputType<TReturn, TContext> =
  | GraphQLOutputType
  | ObjectTypeComposer<TReturn, TContext>
  | EnumTypeComposer<TContext>
  | ScalarTypeComposer<TContext>
  | TypeAsString
  | Resolver<any, TContext, any>
  | InterfaceTypeComposer<TReturn, TContext>
  | UnionTypeComposer<TReturn, TContext>
  | Array<
      | GraphQLOutputType
      | ObjectTypeComposer<TReturn, TContext>
      | EnumTypeComposer<TContext>
      | ScalarTypeComposer<TContext>
      | TypeAsString
      | Resolver<any, TContext, any>
      | InterfaceTypeComposer<TReturn, TContext>
      | UnionTypeComposer<TReturn, TContext>
    >;
\`\`\`

### ArgsMap

\`\`\`js
// Compose Args -----------------------------
export type ArgsMap = { [argName: string]: any };
\`\`\`

### ComposeArgumentType

\`\`\`js
export type ComposeArgumentType =
  | GraphQLInputType
  | TypeAsString
  | InputTypeComposer<any>
  | EnumTypeComposer<any>
  | ScalarTypeComposer<any>
  | Array<
      | GraphQLInputType
      | TypeAsString
      | InputTypeComposer<any>
      | EnumTypeComposer<any>
      | ScalarTypeComposer<any>
    >;
\`\`\`

### ComposeArgumentConfigAsObject

\`\`\`js
export type ComposeArgumentConfigAsObject = {
  type: Thunk<ComposeArgumentType> | GraphQLInputType;
  defaultValue?: any;
  description?: string | null;
  astNode?: InputValueDefinitionNode | null;
} & { $call?: void };
\`\`\`

### ComposeArgumentConfig

\`\`\`js
export type ComposeArgumentConfig =
  | ComposeArgumentConfigAsObject
  | ComposeArgumentType
  | (() => ComposeArgumentConfigAsObject | ComposeArgumentType);
\`\`\`

### ComposeFieldConfigArgumentMap

\`\`\`js
export type ComposeFieldConfigArgumentMap<TArgs = ArgsMap> = {
  [argName in keyof TArgs]: ComposeArgumentConfig
};
\`\`\`

### RelationThunkMap

\`\`\`js
// RELATION -----------------------------
export type RelationThunkMap<TSource, TContext> = {
  [fieldName: string]: Thunk<RelationOpts<TSource, TContext, ArgsMap>>;
};
\`\`\`

### RelationOpts

\`\`\`js
export type RelationOpts<TRelationSource, TSource, TContext, TArgs = ArgsMap> =
  | RelationOptsWithResolver<TRelationSource, TSource, TContext, TArgs>
  | RelationOptsWithFieldConfig<TSource, TContext, TArgs>;
\`\`\`

### RelationOptsWithResolver

\`\`\`js
export type RelationOptsWithResolver<TRelationSource, TSource, TContext, TArgs = ArgsMap> = {
  resolver: Thunk<Resolver<TRelationSource, TContext, TArgs>>;
  prepareArgs?: RelationArgsMapper<TSource, TContext, TArgs>;
  projection?: Partial<ProjectionType>;
  description?: string | null;
  deprecationReason?: string | null;
  catchErrors?: boolean;
};
\`\`\`

### RelationOptsWithFieldConfig

\`\`\`js
export type RelationOptsWithFieldConfig<
  TSource,
  TContext,
  TArgs = ArgsMap
> = ComposeFieldConfigAsObject<TSource, TContext, TArgs> & {
  resolve: GraphQLFieldResolver<TSource, TContext, TArgs>;
};
\`\`\`

### RelationArgsMapperFn

\`\`\`js
export type RelationArgsMapperFn<TSource, TContext, TArgs = ArgsMap> = (
  source: TSource,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => any;
\`\`\`

### RelationArgsMapper

\`\`\`js
export type RelationArgsMapper<TSource, TContext, TArgs = ArgsMap> = {
  [argName: string]:
    | { [key: string]: any }
    | RelationArgsMapperFn<TSource, TContext, TArgs>
    | null
    | void
    | string
    | number
    | any[];
};
\`\`\`

### ObjectTypeComposeDefinition

\`\`\`js
export type ObjectTypeComposeDefinition<TSource, TContext> =
  | TypeAsString
  | ComposeObjectTypeConfig<TSource, TContext>
  | GraphQLObjectType;
\`\`\`
"
`);
});

it('parse ObjectTypeComposer.d.ts', () => {
  expect(TSClassParser.parseFile(file)).toMatchInlineSnapshot(`
Object {
  "classData": Object {
    "constructors": Array [
      Object {
        "documentation": "",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "gqType",
            "type": "GraphQLObjectType",
            "typeChecker": "GraphQLObjectType<any, any, { [key: string]: any; }>",
          },
          Object {
            "documentation": "",
            "name": "schemaComposer",
            "type": "SchemaComposer<TContext>",
            "typeChecker": "any",
          },
        ],
        "type": "ObjectTypeComposer<TSource, TContext>",
      },
    ],
    "documentation": "",
    "methods": Array [
      Object {
        "documentation": "-----------------------------------------------
Field methods
-----------------------------------------------",
        "flags": Object {},
        "name": "getFields",
        "parameters": Array [],
        "type": "ComposeFieldConfigMap<TSource, TContext>",
        "typeChecker": "() => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldNames",
        "parameters": Array [],
        "type": "string[]",
        "typeChecker": "() => string[]",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fields",
            "type": "ComposeFieldConfigMap<TSource, TContext>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(fields: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "hasField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "boolean",
        "typeChecker": "(fieldName: string) => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TArgs = ArgsMap>",
        "name": "setField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "fieldConfig",
            "type": "ComposeFieldConfig<TSource, TContext, TArgs>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "<TArgs = ArgsMap>(fieldName: string, fieldConfig: any) => this",
      },
      Object {
        "documentation": "Add new fields or replace existed in a GraphQL type",
        "flags": Object {},
        "name": "addFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "newFields",
            "type": "ComposeFieldConfigMap<TSource, TContext>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(newFields: any) => this",
      },
      Object {
        "documentation": "Add new fields or replace existed (where field name may have dots)",
        "flags": Object {},
        "name": "addNestedFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "newFields",
            "type": "ComposeFieldConfigMap<TSource, TContext>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(newFields: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TArgs = ArgsMap>",
        "name": "getField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "ComposeFieldConfig<TSource, TContext, TArgs>",
        "typeChecker": "<TArgs = ArgsMap>(fieldName: string) => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "removeField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldNameOrArray",
            "type": "string | string[]",
            "typeChecker": "string | string[]",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldNameOrArray: string | string[]) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "removeOtherFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldNameOrArray",
            "type": "string | string[]",
            "typeChecker": "string | string[]",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldNameOrArray: string | string[]) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TArgs = ArgsMap>",
        "name": "extendField",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "partialFieldConfig",
            "type": "Partial<ComposeFieldConfig<TSource, TContext, TArgs>>",
            "typeChecker": "Partial<any>",
          },
        ],
        "type": "this",
        "typeChecker": "<TArgs = ArgsMap>(fieldName: string, partialFieldConfig: Partial<any>) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "reorderFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "names",
            "type": "string[]",
            "typeChecker": "string[]",
          },
        ],
        "type": "this",
        "typeChecker": "(names: string[]) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "isFieldNonNull",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "boolean",
        "typeChecker": "(fieldName: string) => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldConfig",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "GraphQLFieldConfig<TSource, TContext>",
        "typeChecker": "(fieldName: string) => GraphQLFieldConfig<TSource, TContext, { [argName: string]: any; }>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldType",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "GraphQLOutputType",
        "typeChecker": "(fieldName: string) => GraphQLOutputType",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldTC",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "ObjectTypeComposer<TSource, TContext>",
        "typeChecker": "(fieldName: string) => ObjectTypeComposer<TSource, TContext>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "makeFieldNonNull",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldNameOrArray",
            "type": "string | string[]",
            "typeChecker": "string | string[]",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldNameOrArray: string | string[]) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "makeFieldNullable",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldNameOrArray",
            "type": "string | string[]",
            "typeChecker": "string | string[]",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldNameOrArray: string | string[]) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "deprecateFields",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fields",
            "type": "{
    [fieldName: string]: string;
} | string[] | string",
            "typeChecker": "string | string[] | { [fieldName: string]: string; }",
          },
        ],
        "type": "this",
        "typeChecker": "(fields: string | string[] | { [fieldName: string]: string; }) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldArgs",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "GraphQLFieldConfigArgumentMap",
        "typeChecker": "(fieldName: string) => GraphQLFieldConfigArgumentMap",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "hasFieldArg",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "argName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "boolean",
        "typeChecker": "(fieldName: string, argName: string) => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldArg",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "argName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "GraphQLArgumentConfig",
        "typeChecker": "(fieldName: string, argName: string) => GraphQLArgumentConfig",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldArgType",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "argName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "GraphQLInputType",
        "typeChecker": "(fieldName: string, argName: string) => GraphQLInputType",
      },
      Object {
        "documentation": "-----------------------------------------------
Type methods
-----------------------------------------------",
        "flags": Object {},
        "name": "getType",
        "parameters": Array [],
        "type": "GraphQLObjectType",
        "typeChecker": "() => GraphQLObjectType<any, any, { [key: string]: any; }>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getTypePlural",
        "parameters": Array [],
        "type": "GraphQLList<GraphQLObjectType>",
        "typeChecker": "() => GraphQLList<GraphQLObjectType<any, any, { [key: string]: any; }>>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getTypeNonNull",
        "parameters": Array [],
        "type": "GraphQLNonNull<GraphQLObjectType>",
        "typeChecker": "() => GraphQLNonNull<GraphQLObjectType<any, any, { [key: string]: any; }>>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getTypeName",
        "parameters": Array [],
        "type": "string",
        "typeChecker": "() => string",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setTypeName",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "this",
        "typeChecker": "(name: string) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getDescription",
        "parameters": Array [],
        "type": "string",
        "typeChecker": "() => string",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setDescription",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "description",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "this",
        "typeChecker": "(description: string) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TCloneSource = TSource>",
        "name": "clone",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "newTypeName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "ObjectTypeComposer<TCloneSource, TContext>",
        "typeChecker": "<TCloneSource = TSource>(newTypeName: string) => ObjectTypeComposer<TCloneSource, TContext>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getIsTypeOf",
        "parameters": Array [],
        "type": "GraphQLIsTypeOfFn<TSource, TContext> | null | void",
        "typeChecker": "() => void | GraphQLIsTypeOfFn<TSource, TContext>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setIsTypeOf",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fn",
            "type": "GraphQLIsTypeOfFn<any, any> | null | void",
            "typeChecker": "void | GraphQLIsTypeOfFn<any, any>",
          },
        ],
        "type": "this",
        "typeChecker": "(fn: void | GraphQLIsTypeOfFn<any, any>) => this",
      },
      Object {
        "documentation": "-----------------------------------------------
InputType methods
-----------------------------------------------",
        "flags": Object {},
        "name": "getInputType",
        "parameters": Array [],
        "type": "GraphQLInputObjectType",
        "typeChecker": "() => GraphQLInputObjectType",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "hasInputTypeComposer",
        "parameters": Array [],
        "type": "boolean",
        "typeChecker": "() => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setInputTypeComposer",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "itc",
            "type": "InputTypeComposer<TContext>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(itc: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getInputTypeComposer",
        "parameters": Array [],
        "type": "InputTypeComposer<TContext>",
        "typeChecker": "() => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getITC",
        "parameters": Array [],
        "type": "InputTypeComposer<TContext>",
        "typeChecker": "() => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "removeInputTypeComposer",
        "parameters": Array [],
        "type": "this",
        "typeChecker": "() => this",
      },
      Object {
        "documentation": "-----------------------------------------------
Resolver methods
-----------------------------------------------",
        "flags": Object {},
        "name": "getResolvers",
        "parameters": Array [],
        "type": "Map<string, Resolver<any, TContext, any>>",
        "typeChecker": "() => Map<string, any>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "hasResolver",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "boolean",
        "typeChecker": "(name: string) => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TResolverSource = any, TArgs = ArgsMap>",
        "name": "getResolver",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "middlewares",
            "type": "Array<ResolverMiddleware<TResolverSource, TContext, TArgs>>",
            "typeChecker": "any[]",
          },
        ],
        "type": "Resolver<TResolverSource, TContext, TArgs>",
        "typeChecker": "<TResolverSource = any, TArgs = ArgsMap>(name: string, middlewares?: any[]) => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TResolverSource = any, TArgs = ArgsMap>",
        "name": "setResolver",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "name",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "resolver",
            "type": "Resolver<TResolverSource, TContext, TArgs>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "<TResolverSource = any, TArgs = ArgsMap>(name: string, resolver: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TResolverSource = any, TArgs = ArgsMap>",
        "name": "addResolver",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "resolver",
            "type": "Resolver<TResolverSource, TContext, TArgs> | ResolverOpts<TResolverSource, TContext, TArgs>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "<TResolverSource = any, TArgs = ArgsMap>(resolver: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "removeResolver",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "resolverName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "this",
        "typeChecker": "(resolverName: string) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TResolverSource = any, TArgs = ArgsMap>",
        "name": "wrapResolver",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "resolverName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "cbResolver",
            "type": "ResolverWrapCb<TResolverSource, TSource, TContext, TArgs>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "<TResolverSource = any, TArgs = ArgsMap>(resolverName: string, cbResolver: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TResolverSource = any, TArgs = ArgsMap>",
        "name": "wrapResolverAs",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "resolverName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "fromResolverName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "cbResolver",
            "type": "ResolverWrapCb<TResolverSource, TSource, TContext, TArgs>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "<TResolverSource = any, TArgs = ArgsMap>(resolverName: string, fromResolverName: string, cbResolver: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "generics": "<TResolverSource = any, TArgs = ArgsMap>",
        "name": "wrapResolverResolve",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "resolverName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "cbNextRp",
            "type": "ResolverNextRpCb<TResolverSource, TContext, TArgs>",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "<TResolverSource = any, TArgs = ArgsMap>(resolverName: string, cbNextRp: any) => this",
      },
      Object {
        "documentation": "-----------------------------------------------
Interface methods
-----------------------------------------------",
        "flags": Object {},
        "name": "getInterfaces",
        "parameters": Array [],
        "type": "Array<InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType>",
        "typeChecker": "() => any[]",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setInterfaces",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "interfaces",
            "type": "Array<InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType>",
            "typeChecker": "any[]",
          },
        ],
        "type": "this",
        "typeChecker": "(interfaces: any[]) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "hasInterface",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "iface",
            "type": "string | InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType",
            "typeChecker": "any",
          },
        ],
        "type": "boolean",
        "typeChecker": "(iface: any) => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "addInterface",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "interfaceObj",
            "type": "InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(interfaceObj: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "removeInterface",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "interfaceObj",
            "type": "InterfaceTypeComposer<any, TContext> | GraphQLInterfaceType",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(interfaceObj: any) => this",
      },
      Object {
        "documentation": "-----------------------------------------------
Extensions methods
-----------------------------------------------",
        "flags": Object {},
        "name": "getExtensions",
        "parameters": Array [],
        "type": "Extensions",
        "typeChecker": "() => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setExtensions",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensions",
            "type": "Extensions",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(extensions: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "extendExtensions",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensions",
            "type": "Extensions",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(extensions: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "clearExtensions",
        "parameters": Array [],
        "type": "this",
        "typeChecker": "() => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "any",
        "typeChecker": "(extensionName: string) => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "hasExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "boolean",
        "typeChecker": "(extensionName: string) => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "value",
            "type": "any",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(extensionName: string, value: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "removeExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "this",
        "typeChecker": "(extensionName: string) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldExtensions",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "Extensions",
        "typeChecker": "(fieldName: string) => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setFieldExtensions",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "extensions",
            "type": "Extensions",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldName: string, extensions: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "extendFieldExtensions",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "extensions",
            "type": "Extensions",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldName: string, extensions: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "clearFieldExtensions",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldName: string) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getFieldExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "any",
        "typeChecker": "(fieldName: string, extensionName: string) => any",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "hasFieldExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "boolean",
        "typeChecker": "(fieldName: string, extensionName: string) => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setFieldExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "value",
            "type": "any",
            "typeChecker": "any",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldName: string, extensionName: string, value: any) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "removeFieldExtension",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "extensionName",
            "type": "string",
            "typeChecker": "string",
          },
        ],
        "type": "this",
        "typeChecker": "(fieldName: string, extensionName: string) => this",
      },
      Object {
        "documentation": "-----------------------------------------------
Misc methods
-----------------------------------------------",
        "flags": Object {},
        "generics": "<TRelationSource = any, TArgs = ArgsMap>",
        "name": "addRelation",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fieldName",
            "type": "string",
            "typeChecker": "string",
          },
          Object {
            "documentation": "",
            "name": "relationOpts",
            "type": "RelationOpts<TRelationSource, TSource, TContext, TArgs>",
            "typeChecker": "RelationOpts<TRelationSource, TSource, TContext, TArgs>",
          },
        ],
        "type": "this",
        "typeChecker": "<TRelationSource = any, TArgs = ArgsMap>(fieldName: string, relationOpts: RelationOpts<TRelationSource, TSource, TContext, TArgs>) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getRelations",
        "parameters": Array [],
        "type": "RelationThunkMap<any, TContext>",
        "typeChecker": "() => RelationThunkMap<any, TContext>",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "setRecordIdFn",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "fn",
            "type": "GetRecordIdFn<TSource, TContext>",
            "typeChecker": "GetRecordIdFn<TSource, TContext>",
          },
        ],
        "type": "this",
        "typeChecker": "(fn: GetRecordIdFn<TSource, TContext>) => this",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "hasRecordIdFn",
        "parameters": Array [],
        "type": "boolean",
        "typeChecker": "() => boolean",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "getRecordIdFn",
        "parameters": Array [],
        "type": "GetRecordIdFn<TSource, TContext>",
        "typeChecker": "() => GetRecordIdFn<TSource, TContext>",
      },
      Object {
        "documentation": "Get function that returns record id, from provided object.",
        "flags": Object {},
        "name": "getRecordId",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "source",
            "type": "TSource",
            "typeChecker": "TSource",
          },
          Object {
            "documentation": "",
            "name": "args",
            "type": "ArgsMap",
            "typeChecker": "ArgsMap",
          },
          Object {
            "documentation": "",
            "name": "context",
            "type": "TContext",
            "typeChecker": "TContext",
          },
        ],
        "type": "string | number",
        "typeChecker": "(source: TSource, args?: ArgsMap, context?: TContext) => string | number",
      },
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "get",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "path",
            "type": "string | string[]",
            "typeChecker": "string | string[]",
          },
        ],
        "type": "any",
        "typeChecker": "(path: string | string[]) => any",
      },
    ],
    "name": "ObjectTypeComposer",
    "properties": Array [
      Object {
        "documentation": "",
        "flags": Object {},
        "name": "schemaComposer",
        "type": "SchemaComposer<TContext>",
        "typeChecker": "any",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "protected": true,
        },
        "name": "gqType",
        "type": "GraphQLObjectTypeExtended<TSource, TContext>",
        "typeChecker": "GraphQLObjectTypeExtended<TSource, TContext>",
      },
    ],
    "staticMethods": Array [
      Object {
        "documentation": "",
        "flags": Object {
          "static": true,
        },
        "generics": "<TSrc = any, TCtx = any>",
        "name": "create",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "typeDef",
            "type": "ObjectTypeComposeDefinition<TSrc, TCtx>",
            "typeChecker": "any",
          },
          Object {
            "documentation": "",
            "name": "schemaComposer",
            "type": "SchemaComposer<TCtx>",
            "typeChecker": "any",
          },
        ],
        "type": "ObjectTypeComposer<TSrc, TCtx>",
        "typeChecker": "<TSrc = any, TCtx = any>(typeDef: any, schemaComposer: any) => ObjectTypeComposer<TSrc, TCtx>",
      },
      Object {
        "documentation": "",
        "flags": Object {
          "static": true,
        },
        "generics": "<TSrc = any, TCtx = any>",
        "name": "createTemp",
        "parameters": Array [
          Object {
            "documentation": "",
            "name": "typeDef",
            "type": "ObjectTypeComposeDefinition<TSrc, TCtx>",
            "typeChecker": "any",
          },
          Object {
            "documentation": "",
            "name": "schemaComposer",
            "type": "SchemaComposer<TCtx>",
            "typeChecker": "any",
          },
        ],
        "type": "ObjectTypeComposer<TSrc, TCtx>",
        "typeChecker": "<TSrc = any, TCtx = any>(typeDef: any, schemaComposer?: any) => ObjectTypeComposer<TSrc, TCtx>",
      },
    ],
    "staticProperties": Array [],
    "type": "",
    "typeChecker": "typeof ObjectTypeComposer",
  },
  "interfaces": Array [
    Object {
      "code": "

export type GetRecordIdFn<TSource, TContext> = (
  source: TSource,
  args: any,
  context: TContext
) => string;",
      "name": " GetRecordIdFn",
    },
    Object {
      "code": "

export type GraphQLObjectTypeExtended<TSource, TContext> = GraphQLObjectType & {
  _gqcInputTypeComposer?: InputTypeComposer<TContext>;
  _gqcResolvers?: Map<string, Resolver<TSource, TContext>>;
  _gqcGetRecordIdFn?: GetRecordIdFn<TSource, TContext>;
  _gqcRelations?: RelationThunkMap<TSource, TContext>;
  _gqcFields?: ComposeFieldConfigMap<TSource, TContext>;
  _gqcInterfaces?: Array<GraphQLInterfaceType | InterfaceTypeComposer<any, TContext>>;
  _gqcExtensions?: Extensions;
  description: string | null;
};",
      "name": " GraphQLObjectTypeExtended",
    },
    Object {
      "code": "

export type ComposeObjectTypeConfig<TSource, TContext> = {
  name: string;
  interfaces?: Thunk<GraphQLInterfaceType[] | null>;
  fields?: Thunk<ComposeFieldConfigMap<TSource, TContext>>;
  isTypeOf?: GraphQLIsTypeOfFn<TSource, TContext> | null;
  description?: string | null;
  isIntrospection?: boolean;
  extensions?: Extensions;
};",
      "name": " ComposeObjectTypeConfig",
    },
    Object {
      "code": "

// extended GraphQLFieldConfigMap
export type ComposeFieldConfigMap<TSource, TContext> = ObjMap<
  ComposeFieldConfig<TSource, TContext>
>;",
      "name": " ComposeFieldConfigMap",
    },
    Object {
      "code": "

export type ComposeFieldConfig<TSource, TContext, TArgs = ArgsMap> =
  | ComposeFieldConfigAsObject<TSource, TContext, TArgs>
  | ComposeOutputType<any /* TReturn */, TContext>
  | Thunk<
      | ComposeFieldConfigAsObject<TSource, TContext, TArgs>
      | ComposeOutputType<any /* TReturn */, TContext>
    >;",
      "name": " ComposeFieldConfig",
    },
    Object {
      "code": "

// extended GraphQLFieldConfig
export type GraphqlFieldConfigExtended<TSource, TContext> = GraphQLFieldConfig<
  TSource,
  TContext
> & { projection?: any };",
      "name": " GraphqlFieldConfigExtended",
    },
    Object {
      "code": "

export type ComposeFieldConfigAsObject<TSource, TContext, TArgs = ArgsMap> = {
  type: Thunk<ComposeOutputType<any /* TReturn */, TContext>> | GraphQLOutputType;
  args?: ComposeFieldConfigArgumentMap<TArgs>;
  resolve?: GraphQLFieldResolver<TSource, TContext, TArgs>;
  subscribe?: GraphQLFieldResolver<TSource, TContext>;
  deprecationReason?: string | null;
  description?: string | null;
  astNode?: FieldDefinitionNode | null;
  extensions?: Extensions;
  [key: string]: any;
} & { $call?: void };",
      "name": " ComposeFieldConfigAsObject",
    },
    Object {
      "code": "

// Output type should not have \`TSource\`. It should not affect on main Type source!
// extended GraphQLOutputType
export type ComposeOutputType<TReturn, TContext> =
  | GraphQLOutputType
  | ObjectTypeComposer<TReturn, TContext>
  | EnumTypeComposer<TContext>
  | ScalarTypeComposer<TContext>
  | TypeAsString
  | Resolver<any, TContext, any>
  | InterfaceTypeComposer<TReturn, TContext>
  | UnionTypeComposer<TReturn, TContext>
  | Array<
      | GraphQLOutputType
      | ObjectTypeComposer<TReturn, TContext>
      | EnumTypeComposer<TContext>
      | ScalarTypeComposer<TContext>
      | TypeAsString
      | Resolver<any, TContext, any>
      | InterfaceTypeComposer<TReturn, TContext>
      | UnionTypeComposer<TReturn, TContext>
    >;",
      "name": " ComposeOutputType",
    },
    Object {
      "code": "

// Compose Args -----------------------------
export type ArgsMap = { [argName: string]: any };",
      "name": " ArgsMap",
    },
    Object {
      "code": "
export type ComposeArgumentType =
  | GraphQLInputType
  | TypeAsString
  | InputTypeComposer<any>
  | EnumTypeComposer<any>
  | ScalarTypeComposer<any>
  | Array<
      | GraphQLInputType
      | TypeAsString
      | InputTypeComposer<any>
      | EnumTypeComposer<any>
      | ScalarTypeComposer<any>
    >;",
      "name": " ComposeArgumentType",
    },
    Object {
      "code": "

export type ComposeArgumentConfigAsObject = {
  type: Thunk<ComposeArgumentType> | GraphQLInputType;
  defaultValue?: any;
  description?: string | null;
  astNode?: InputValueDefinitionNode | null;
} & { $call?: void };",
      "name": " ComposeArgumentConfigAsObject",
    },
    Object {
      "code": "

export type ComposeArgumentConfig =
  | ComposeArgumentConfigAsObject
  | ComposeArgumentType
  | (() => ComposeArgumentConfigAsObject | ComposeArgumentType);",
      "name": " ComposeArgumentConfig",
    },
    Object {
      "code": "

export type ComposeFieldConfigArgumentMap<TArgs = ArgsMap> = {
  [argName in keyof TArgs]: ComposeArgumentConfig
};",
      "name": " ComposeFieldConfigArgumentMap",
    },
    Object {
      "code": "

// RELATION -----------------------------
export type RelationThunkMap<TSource, TContext> = {
  [fieldName: string]: Thunk<RelationOpts<TSource, TContext, ArgsMap>>;
};",
      "name": " RelationThunkMap",
    },
    Object {
      "code": "

export type RelationOpts<TRelationSource, TSource, TContext, TArgs = ArgsMap> =
  | RelationOptsWithResolver<TRelationSource, TSource, TContext, TArgs>
  | RelationOptsWithFieldConfig<TSource, TContext, TArgs>;",
      "name": " RelationOpts",
    },
    Object {
      "code": "

export type RelationOptsWithResolver<TRelationSource, TSource, TContext, TArgs = ArgsMap> = {
  resolver: Thunk<Resolver<TRelationSource, TContext, TArgs>>;
  prepareArgs?: RelationArgsMapper<TSource, TContext, TArgs>;
  projection?: Partial<ProjectionType>;
  description?: string | null;
  deprecationReason?: string | null;
  catchErrors?: boolean;
};",
      "name": " RelationOptsWithResolver",
    },
    Object {
      "code": "

export type RelationOptsWithFieldConfig<
  TSource,
  TContext,
  TArgs = ArgsMap
> = ComposeFieldConfigAsObject<TSource, TContext, TArgs> & {
  resolve: GraphQLFieldResolver<TSource, TContext, TArgs>;
};",
      "name": " RelationOptsWithFieldConfig",
    },
    Object {
      "code": "

export type RelationArgsMapperFn<TSource, TContext, TArgs = ArgsMap> = (
  source: TSource,
  args: TArgs,
  context: TContext,
  info: GraphQLResolveInfo
) => any;",
      "name": " RelationArgsMapperFn",
    },
    Object {
      "code": "

export type RelationArgsMapper<TSource, TContext, TArgs = ArgsMap> = {
  [argName: string]:
    | { [key: string]: any }
    | RelationArgsMapperFn<TSource, TContext, TArgs>
    | null
    | void
    | string
    | number
    | any[];
};",
      "name": " RelationArgsMapper",
    },
    Object {
      "code": "

export type ObjectTypeComposeDefinition<TSource, TContext> =
  | TypeAsString
  | ComposeObjectTypeConfig<TSource, TContext>
  | GraphQLObjectType;",
      "name": " ObjectTypeComposeDefinition",
    },
  ],
}
`);
});
